### ISSUE TITLE
网络变化次数较多，请稳定网络环境

### ISSUE THREAD

**Issue by fjqzaxljm** [hahahrfool/myTTnode#1]
联通的，有公网ip，最近一出现“网络变化次数较多”一直没什么收益。不知道什么原因。

**Comment by hahahrfool** [comment]
我没有遇到过这种情况。你上传速度多少？

**Comment by fjqzaxljm** [comment]
30左右。

hahafool <notifications@github.com> 于 2021年1月22日周五 19:15写道：
